version: '3'
services:
  app:
    build: .
    ports:
      - 8091:1234
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
